// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlnb1szOwg_0bzZL82XHHJb2_98VmaPeE',
    appId: '1:635727463384:web:40c9f83c6e8c4ea8e168ad',
    messagingSenderId: '635727463384',
    projectId: 'fun-kits',
    authDomain: 'fun-kits.firebaseapp.com',
    storageBucket: 'fun-kits.firebasestorage.app',
    measurementId: 'G-JDKC69N459',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLTPECYKBZBb5PoQdF13_dMjjjL7N1G84',
    appId: '1:635727463384:android:d646a6fbb9c19558e168ad',
    messagingSenderId: '635727463384',
    projectId: 'fun-kits',
    storageBucket: 'fun-kits.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkJ_zJrmVfpTC3FjUmUe3wI0wMm9PvKI4',
    appId: '1:635727463384:ios:3faf047d3e8d1392e168ad',
    messagingSenderId: '635727463384',
    projectId: 'fun-kits',
    storageBucket: 'fun-kits.firebasestorage.app',
    iosClientId: '635727463384-hr07fij59qut76tost41cna49ocrmi2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkJ_zJrmVfpTC3FjUmUe3wI0wMm9PvKI4',
    appId: '1:635727463384:ios:3faf047d3e8d1392e168ad',
    messagingSenderId: '635727463384',
    projectId: 'fun-kits',
    storageBucket: 'fun-kits.firebasestorage.app',
    iosClientId: '635727463384-hr07fij59qut76tost41cna49ocrmi2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlnb1szOwg_0bzZL82XHHJb2_98VmaPeE',
    appId: '1:635727463384:web:9e03a283009ade09e168ad',
    messagingSenderId: '635727463384',
    projectId: 'fun-kits',
    authDomain: 'fun-kits.firebaseapp.com',
    storageBucket: 'fun-kits.firebasestorage.app',
    measurementId: 'G-YXYFX98ZG6',
  );
}
